function [fitresult, gof] = createFit(x, spindle_amplitude)
%CREATEFIT(X,SPINDLE_NEG)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: spindle_amplitude
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Apr-2022 13:04:37


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, spindle_amplitude);

% Set up fittype and options.
ft = fittype( 'poly2' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% % Plot fit with data.
% figure( 'Name', '2nd Degree Poly fit of odd/even side of Spindle' );
% h = plot( fitresult, xData, yData );
% legend( h, 'Spindle', '2nd Degree Poly fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'Datapoints', 'Interpreter', 'none' );
% ylabel( 'Amplitude', 'Interpreter', 'none' );
% grid on


